# Generated by Django 3.1.1 on 2020-09-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='deployment_id',
            field=models.PositiveIntegerField(),
        ),
    ]
