# Generated by Django 3.1.1 on 2020-09-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200911_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrusionattempt',
            name='subnet',
            field=models.CharField(default='N/A', max_length=32),
        ),
    ]
