# Generated by Django 3.1.1 on 2020-09-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_intrusionattempt_subnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrusionattempt',
            name='date',
        ),
    ]
